// copy-icons.mjs — generate internal/app/icons.go from Material Symbols SVGs.
//
// The project ships a small curated set of Material Symbols (Apache-2.0,
// google/material-design-icons) as trusted server-resolved inline SVGs. The
// generated map is embedded in the Go binary: consumers never fetch icon
// files at runtime, and every glyph is themeable via currentColor.
//
// Contract enforced here (and by styles_icon_test.go):
//   - every SVG is aria-hidden + focusable=false (decorative by default)
//   - fill is currentColor so the glyph matches surrounding text tokens
//   - the set is a curated allowlist, not the whole 7.8k-icon package

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url)) + "/..";
// Resolve the icon package through Node's module resolution (works under npm
// workspace hoisting: the package may live at the root node_modules or
// nested under site/node_modules — never hardcode ../node_modules).
const ICON_ROOT = dirname(fileURLToPath(import.meta.resolve("@material-symbols/svg-400/package.json")));
const SRC = ICON_ROOT + "/rounded";
const OUT = ROOT + "/internal/app/icons.go";

// Allowlist: names resolve to <name>.svg in @material-symbols/svg-400/rounded.
const ICONS = [
  "add",
  "arrow_back",
  "arrow_downward",
  "arrow_forward",
  "arrow_upward",
  "check",
  "chevron_left",
  "chevron_right",
  "close",
  "delete",
  "edit",
  "error",
  "home",
  "info",
  "menu",
  "more_vert",
  "refresh",
  "save",
  "search",
  "settings",
  "warning",
  "person",
  "notifications",
  "share",
  "star",
  "thumb_up",
  "visibility",
  "visibility_off",
  "lock",
  "send",
  "download",
  "upload",
  "calendar_today",
  "schedule",
  "more_horiz",
  "add_circle",
  "dark_mode",
  "light_mode",
];

// stripSvg turns a Material Symbols source file into the inner content of a
// trusted inline glyph: it drops the <svg> wrapper and keeps only the inner
// elements (paths, groups). The generated Go constant re-wraps them with the
// project's own class, aria contract, and currentColor fill, preserving the
// source viewBox — Material Symbols paths use a 960-grid coordinate space,
// and the .ui-icon CSS class controls the rendered size.
function stripSvg(source) {
  const inner = source.replace(/^<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  return inner.trim();
}

// viewBoxOf extracts the source viewBox (for example "0 -960 960 960") so the
// generated glyph keeps the coordinate space its paths were authored in.
function viewBoxOf(source) {
  const match = source.match(/viewBox="([^"]+)"/);
  return match ? match[1] : "0 0 24 24";
}

let generated = `// Code generated by scripts/copy-icons.mjs; DO NOT EDIT.
//
// Trusted, internal, decorative Material Symbols glyphs (Apache-2.0,
// https://github.com/google/material-design-icons). Every glyph is resolved
// server-side as trusted template.HTML markup; never place user input in
// these strings. The set is a curated allowlist — see scripts/copy-icons.mjs.

package app

import "html/template"

// iconSVGs is the curated inline-SVG map served by the Icon primitive. Each
// glyph is aria-hidden and unfocusable by contract; the surrounding visible
// text supplies the accessible name. fill=currentColor keeps the glyph at
// the surrounding text's contrast in every theme, including forced-colors.
var iconSVGs = map[string]template.HTML{ // #nosec G203 -- trusted, internal decorative glyphs.
`;

const rows = [];
for (const name of ICONS) {
  const source = await readFile(`${SRC}/${name}.svg`, "utf8");
  const inner = stripSvg(source);
  const viewBox = viewBoxOf(source);
  rows.push(`\t"${name}": \`<svg class="ui-icon" aria-hidden="true" focusable="false" viewBox="${viewBox}" fill="currentColor">${inner}</svg>\`,`);
}

generated += rows.join("\n");
generated += `\n}\n\n// iconSVG returns the trusted inline glyph for name, or nil when the name is
// not part of the curated set. Callers render the result with template.HTML
// semantics only — the map is compile-time constant, never user input.
func iconSVG(name string) template.HTML {
	return iconSVGs[name]
}
`;

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, generated);
console.log(`generated ${OUT} with ${rows.length} icons`);
